# Generated by Django 4.2.7 on 2024-08-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_intake_tracking", "0002_alter_dailyintaketracking_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyintaketracking",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
