# Generated by Django 4.2.7 on 2024-08-25 03:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("daily_intake_tracking", "0003_alter_dailyintaketracking_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyintaketracking",
            unique_together={("date", "user_id")},
        ),
    ]
