# Generated by Django 4.2.7 on 2024-08-26 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_intake_tracking", "0004_alter_dailyintaketracking_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyintaketracking",
            name="current_calories",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="dailyintaketracking",
            name="current_carbs",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="dailyintaketracking",
            name="current_fats",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="dailyintaketracking",
            name="current_protein",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="dailyintaketracking",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="dailyintaketracking",
            name="goal_calories",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="dailyintaketracking",
            name="goal_carbs",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="dailyintaketracking",
            name="goal_fats",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="dailyintaketracking",
            name="goal_protein",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000),
                ]
            ),
        ),
    ]
