# Generated by Django 4.2.7 on 2024-09-11 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_intake_tracking", "0006_foodentrytracking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyintaketracking",
            name="current_calories",
        ),
        migrations.RemoveField(
            model_name="dailyintaketracking",
            name="current_carbs",
        ),
        migrations.RemoveField(
            model_name="dailyintaketracking",
            name="current_fats",
        ),
        migrations.RemoveField(
            model_name="dailyintaketracking",
            name="current_protein",
        ),
    ]
