# Generated by Django 4.2.7 on 2025-07-04 22:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("daily_intake_tracking", "0007_remove_dailyintaketracking_current_calories_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DailyIntakeTracking",
            new_name="DailyMacronutrientGoal",
        ),
    ]
