# Generated by Django 4.2.7 on 2025-07-05 00:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("daily_intake_tracking", "0008_rename_dailyintaketracking_dailymacronutrientgoal"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FoodEntryTracking",
            new_name="FoodEntry",
        ),
    ]
