# Generated by Django 4.2.7 on 2025-07-09 06:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only alphabetic characters are allowed.", regex="^[a-zA-Z]+$"
                            )
                        ],
                    ),
                ),
                (
                    "measurement_system",
                    models.CharField(choices=[("Metric", "Metric"), ("Imperial", "Imperial")], max_length=8),
                ),
            ],
        ),
    ]
