# fly.toml app configuration file generated for radix-fitness-api on 2025-07-26T18:21:37+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'radix-fitness-api'
primary_region = 'syd'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
