# Generated by Django 4.2.7 on 2025-07-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailymacronutrientgoal",
            name="goal_calories",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="dailymacronutrientgoal",
            name="goal_carbs",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="dailymacronutrientgoal",
            name="goal_fats",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="dailymacronutrientgoal",
            name="goal_protein",
            field=models.FloatField(),
        ),
    ]
