# Generated by Django 4.2.7 on 2024-01-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weights',
            old_name='profile',
            new_name='profile_id',
        ),
    ]
