# Generated by Django 4.2.7 on 2024-01-07 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weights', '0002_rename_profile_weights_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weights',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='weights',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
