# Generated by Django 4.2.7 on 2024-04-02 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("weights", "0002_alter_weightgoal_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightgoal",
            name="user_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
