# Generated by Django 4.2.7 on 2025-07-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodentry",
            name="food_weight",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="foodentry",
            name="total_calories",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="foodentry",
            name="total_carbs",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="foodentry",
            name="total_fats",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="foodentry",
            name="total_protein",
            field=models.FloatField(),
        ),
    ]
