# Generated by Django 4.2.7 on 2025-07-21 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0002_alter_foodentry_food_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodentry",
            name="food_weight",
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="foodentry",
            name="total_calories",
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="foodentry",
            name="total_carbs",
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="foodentry",
            name="total_fats",
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="foodentry",
            name="total_protein",
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
