name: Tests
on:
  pull_request:
    paths:
      - '**.py'
  push:
jobs:
  Run-Tests:
    runs-on: ubuntu-20.04
    env:
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.11'

      - name: Setup Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ${{ github.workspace}}/app/requirements.txt

      - name: Create .dev.env file
        working-directory: app/backend
        run: |
          echo ${{ secrets.DEV_DOT_ENV }} > .dev.env

      - name: Test isort
        run: python -m isort --check .

      - name: Test Black
        run: python -m black --check .

      - name: Test Django models
        working-directory: app
        run: python manage.py test --parallel auto
