name: Tests
on:
  pull_request:
    paths:
      - '**.py'
  push:
    paths:
      - '**.py'
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.11'

      - name: Setup Python dependencies
        run: python -m pip install ${{ github.workspace }}\app\requirements.txt

      - name: Test isort
        run: python -m isort --check .

      - name: Test Black
        run: python -m black --check .
